#@ load("@ytt:data", "data")

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-acme-prod
  namespace: cert-manager
spec:
  acme:
    email: #@ data.values.email
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:         
        ingress:           
          class: contour 