---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-cart
  description: ACME Fitness Store Cart Service
  tags:
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=acme-cart'
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: fitness-store
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-catalog
  description: ACME Fitness Store Catalog Service
  tags:
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=acme-catalog'
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: fitness-store
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-identity
  description: ACME Fitness Store Identity Service
  tags:
    - java
    - spring
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=acme-identity'
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: fitness-store  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-order
  description: ACME Fitness Store  Order Service
  tags:
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=acme-order'
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: fitness-store
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-payment
  description: ACME Fitness Store Payment Service
  tags:
    - java
    - spring
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=acme-payment'
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: fitness-store
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-shopping
  description: ACME Fitness Store Shopping Service
  tags:
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=acme-shopping'
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: fitness-store
