name: Deploy Identity
on:
  workflow_dispatch:
    inputs: { }
  push:
    branches:
      - Azure
    paths:
      - 'apps/acme-identity/**'
env:
  SPRING_APPS_SERVICE: ${{ secrets.TF_PROJECT_NAME }}-asa
  RESOURCE_GROUP: ${{ secrets.TF_PROJECT_NAME }}-grp
  KEY_VAULT: ${{ secrets.TF_PROJECT_NAME }}-keyvault
  IDENTITY_SERVICE_APP: identity-service

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/acme-identity
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test #TODO: failing test
          build-root-directory: apps/acme-identity
      - name: Set up Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Azure Spring Extension
        run: az extension add --name spring
      - name: Deploy Identity
        run: |
          keyvault_uri=$(az keyvault show \
           --resource-group ${RESOURCE_GROUP} \
           --name ${KEY_VAULT} | jq -r '.properties.vaultUri')

          az spring app deploy \
            --name ${IDENTITY_SERVICE_APP} \
            --resource-group "$RESOURCE_GROUP" \
            --service "$SPRING_APPS_SERVICE" \
            --env "SPRING_CLOUD_AZURE_KEYVAULT_SECRET_PROPERTY_SOURCES_0_ENDPOINT=${keyvault_uri}" "SPRING_CLOUD_AZURE_KEYVAULT_SECRET_PROPERTY_SOURCES_0_NAME='acme-fitness-store-vault'" "SPRING_PROFILES_ACTIVE=default,key-vault" \
            --config-file-pattern identity/default,identity/key-vault \
            --source-path ./
