name: Deploy Order
on:
  workflow_dispatch:
    inputs: { }
  push:
    branches:
      - Azure
    paths:
      - 'apps/acme-order/**'
env:
  SPRING_APPS_SERVICE: ${{ secrets.TF_PROJECT_NAME }}-asa
  RESOURCE_GROUP: ${{ secrets.TF_PROJECT_NAME }}-grp
  KEY_VAULT: ${{ secrets.TF_PROJECT_NAME }}-keyvault
  CUSTOM_BUILDER: no-bindings-builder
  ORDER_SERVICE_APP: order-service

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/acme-order
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v2
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Set up Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Azure Spring Extension
        run: az extension add --name spring
      - name: Deploy Order
        run: |
          keyvault_uri=$(az keyvault show \
           --resource-group ${RESOURCE_GROUP} \
           --name ${KEY_VAULT} | jq -r '.properties.vaultUri')

          gateway_url=$(az spring gateway show \
            --resource-group ${RESOURCE_GROUP} \
            --service ${SPRING_APPS_SERVICE} | jq -r '.properties.url')

          az spring app deploy \
            --name ${ORDER_SERVICE_APP} \
            --resource-group "$RESOURCE_GROUP" \
            --service "$SPRING_APPS_SERVICE" \
            --builder ${CUSTOM_BUILDER} \
            --env "DatabaseProvider=Postgres" "AcmeServiceSettings__AuthUrl=https://${gateway_url}" "ConnectionStrings__KeyVaultUri=$keyvault_uri" \
            --source-path ./
